node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/kredki/devonfw-tutorial-sources.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'M3'
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
          bat(/call projekt.bat/)
         //bat(/cd jump-the-queue\java\jtqj\ \n"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
         //bat(/"${mvnHome}\bin\mvn" clean package "-Dmaven.test.failure.ignore" "-Dproject.basedir=jump-the-queue\java\jtqj\"/)
      }
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archiveArtifacts 'jump-the-queue/java/jtqj/api/target/*.jar'
   }
}
